In [1]:
import numpy as np

In [2]:
# a. Create a null vector of size 10 but the fifth value which is 1

N = 10
ind = 5 - 1 # zero based
null_vector = np.zeros(N)
null_vector[ind] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
# b. Create a vector with values ranging from 10 to 49

vector = np.array(range(10, 50))
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
# c. Reverse a vector (first element becomes last)

reversed_vector = np.array(list(reversed(vector)))
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
# d. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# e. Find indices of non-zero elements from [1,2,0,0,4,0]

vector = np.array([1,2,0,0,4,0])
non_zero_elements_indices = np.nonzero(vector)
print(non_zero_elements_indices)

(array([0, 1, 4]),)


In [7]:
# f. Create a random vector of size 30 and find the mean value

random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)

0.4964862542622623


In [8]:
# g. Create a 2d array with 1 on the border and 0 inside

arr = np.ones((5, 5))

# Slicing [rows, columns]
# Start at row 1, stop before the last row
# Start at column 1, stop before last column
arr[1:-1, 1:-1] = 0

print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
# h. Create a 8x8 matrix and fill it with a checkerboard pattern

checkerboard_matrix = np.zeros(64).reshape(8, 8)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1

print(checkerboard_matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [58]:
# i. Create a checkerboard 8x8 matrix using the tile function

checkerboard_matrix = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [62]:
# j. Given a 1D array, negate all elements which are between 3 and 8, in place

Z = np.arange(11)
print(Z)

Z[(Z > 3) & (Z < 8)] *= -1 # Create boolean mask
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [69]:
# k. Create a random vector of size 10 and sort it

Z = np.random.random(10)
print(Z)

Z = np.sort(Z)
print("Sorted Z from smallest to largest: \n", Z)

[0.76011487 0.27771057 0.98541659 0.91735232 0.72021934 0.69888631
 0.80138267 0.68874055 0.58954431 0.96739305]
Sorted Z from smallest to largest: 
 [0.27771057 0.58954431 0.68874055 0.69888631 0.72021934 0.76011487
 0.80138267 0.91735232 0.96739305 0.98541659]


In [92]:
# l. Consider two random array A anb B, check if they are equal

A = np.random.randint(0,2,5)
print(A)
B = np.random.randint(0,2,5)
print(B)

equal = np.array_equal(A, B)
print(equal)

[0 1 0 1 1]
[0 1 0 1 0]
True


In [10]:
# m. How to calculate the square of every number in an array in place (without creating temporaries)?

Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
print(Z)

np.square(Z, out = Z)
print(Z)
print(Z.dtype)

int32
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
int32


In [9]:
# n. How to get the diagonal of a dot product?

A = np.arange(9).reshape(3,3)
B = A + 1

C = np.dot(A,B)

D = np.diagonal(C)
print(D)

[ 18  66 132]
